---
- name: set system locale
  lineinfile:
    path: /etc/default/locale
    regexp: "^LANG="
    line: "LANG={{ locale }}"

- name: generate locale
  command: "locale-gen {{ locale }}"

- name: set root password
  shell: "echo 'root:{{ root_password }}' | chpasswd"

- name: set root authorized key
  authorized_key:
    key: "{{ root_authorized_key }}"
    user: root
  when: root_authorized_key is defined

- name: create ansible user
  user:
    name: ansible
    comment: Ansible User
  when: ansible_authorized_key is defined

- name: set ansible authorized key
  authorized_key:
    key: "{{ ansible_authorized_key }}"
    user: ansible
  when: ansible_authorized_key is defined

- name: disable ansible password
  command: usermod -p '!' ansible
  when: ansible_authorized_key is defined

- name: allow ansible passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^ansible"
    line: "ansible ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
  when: ansible_authorized_key is defined

- name: install default netplan config
  copy:
    src: dhcp.yaml
    dest: /etc/netplan/dhcp.yaml

- name: fix zfs mount ordering
  block:
    - command: "zfs set mountpoint=legacy rpool/var/log"
    - command: "zfs set mountpoint=legacy rpool/var/tmp"
    - lineinfile:
        path: /etc/fstab
        regexp: "^rpool/var/log"
        line: "rpool/var/log /var/log zfs noatime,nodev,noexec,nosuid 0 0"
    - lineinfile:
        path: /etc/fstab
        regexp: "^rpool/var/tmp"
        line: "rpool/var/tmp /var/tmp zfs noatime,nodev,nosuid 0 0"

  